[package]
authors = ["Akira1364"]
description = "A port of a combination of the C++ and D ports of my Free Pascal \"Binary Trees\" benchmark implementation, once again written just out of curiosity."
edition = "2018"
include = ["Cargo.toml", "LICENCE-MIT", "src/**/*"]
license = "MIT"
name = "binarytrees_benchmark"
readme = "README.md"
repository = "https://github.com/Akira13641/BinaryTreesBenchmarkRust"
version = "0.0.1"

[profile.release]
lto = true
panic = "abort"

[dependencies]
rayon = "1.3.0"
